/* Writes README.md from profile.config.json.
 *
 *   node scripts/readme.mjs
 *
 * Run it by hand after changing projects or links; the images themselves are
 * rebuilt by the workflow, the README only points at them.
 */

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const cfg = JSON.parse(await readFile(path.join(root, "profile.config.json"), "utf8"));
const RAW = `https://raw.githubusercontent.com/${cfg.github}/${cfg.github}/output`;

// One line each: whitespace inside an <a> renders as an underlined gap.
const pic = (name, alt, width = "100%") =>
  `<picture><source media="(prefers-color-scheme: dark)" srcset="${RAW}/${name}-dark.svg"><source media="(prefers-color-scheme: light)" srcset="${RAW}/${name}-light.svg"><img alt="${alt}" src="${RAW}/${name}-dark.svg" width="${width}"></picture>`;
const link = (href, inner) => `<a href="${href}">${inner}</a>`;

const LABEL = { portfolio: "Portfolio", linkedin: "LinkedIn", email: "Email", codeforces: "Codeforces", leetcode: "LeetCode", codechef: "CodeChef" };
const buttons = ["portfolio", "linkedin", "email", "codeforces", "leetcode", "codechef"]
  .map((k) => link(cfg.links[k], pic(`btn-${k}`, LABEL[k], "")).replace(' width=""', ' height="40"'))
  .join("\n");

const cards = cfg.projects.map((p) => link(`https://github.com/${p.repo}`, pic(`card-${p.id}`, `${p.title}: ${p.line}`, "49%"))).join("\n");
const sites = cfg.projects.filter((p) => p.site).map((p) => `<a href="${p.site}">${p.title}</a>`).join(" · ");

const md = `<!-- Generated by scripts/readme.mjs from profile.config.json. Images rebuild every 6 hours: .github/workflows/profile.yml -->

${link(cfg.links.portfolio, pic("hero", `${cfg.name}: ${cfg.tagline}`))}

<p align="center">
${buttons}
</p>

${pic("scoreboard", "Codeforces, LeetCode and CodeChef, live")}

### Built From Scratch

<p align="center">
${cards}
</p>

<p align="center"><sub>Live Sites: ${sites}</sub></p>

${pic("city", "The last year of contributions, drawn as a city")}

${pic("now", "Latest pushes")}

${pic("stack", "Tech stack")}

<p align="center"><sub>Every image here is an SVG drawn by <a href="scripts">a few hundred lines of JavaScript</a> from public data, redrawn every six hours by <a href=".github/workflows/profile.yml">GitHub Actions</a>. No third-party stat cards.</sub></p>
`;

await writeFile(path.join(root, "README.md"), md);
console.log("README.md written");
